export default {
  ADD_POST: 'ADD_POST',
  EDIT_POST: 'EDIT_POST',
  DELETE_POST: 'DELETE_POST',
  UPDATE_POST: 'UPDATE_POST',
  SET_POSTS: 'SET_POSTS',
  GET_INIT_POSTS_ASYNC: 'GET_INIT_POSTS_ASYNC'
};
